// nodes_data.js
const nodesData = [
    { id: 1, label: "Persönlichkeitsentwicklung", group: "main", color: "#FF6B6B", x: 0, y: 0 },
    { id: 2, label: "Ziele setzen", group: "sub", color: "#4ECDC4", title: "Klare und erreichbare Ziele definieren." },
    { id: 3, label: "Selbstreflexion", group: "sub", color: "#4ECDC4", title: "Regelmäßige Selbstbewertung und -analyse." },
    { id: 4, label: "Achtsamkeit", group: "sub", color: "#4ECDC4", title: "Bewusstes Erleben des gegenwärtigen Moments." },
    { id: 5, label: "Journaling", group: "tools", color: "#FFEEAD", title: "Tägliches Führen eines Tagebuchs zur Selbstreflexion." },
    { id: 6, label: "Meditation", group: "tools", color: "#FFEEAD", title: "Praktiken zur Förderung von Achtsamkeit und Entspannung." },
    { id: 7, label: "SMART-Methode", group: "tools", color: "#FFEEAD", title: "Spezifisch, Messbar, Erreichbar, Relevant, Terminiert." },
    { id: 8, label: "Karriereplanung", group: "main", color: "#FF6B6B", x: 200, y: 0 },
    { id: 9, label: "Fähigkeiten", group: "sub", color: "#4ECDC4", title: "Identifizierung und Entwicklung von Fähigkeiten." },
    { id: 10, label: "Netzwerken", group: "sub", color: "#4ECDC4", title: "Aufbau und Pflege beruflicher Kontakte." },
    { id: 11, label: "Weiterbildung", group: "sub", color: "#4ECDC4", title: "Lebenslanges Lernen und Anpassung an Veränderungen." },
    { id: 12, label: "LinkedIn", group: "tools", color: "#FFEEAD", title: "Professionelles Netzwerkprofil pflegen." },
    { id: 13, label: "Coursera", group: "tools", color: "#FFEEAD", title: "Online-Kurse zur Weiterbildung." },
    { id: 14, label: "Mentoring", group: "tools", color: "#FFEEAD", title: "Lernen von erfahrenen Fachleuten." },
    { id: 15, label: "Gesundheit", group: "main", color: "#FF6B6B", x: -200, y: 0 },
    { id: 16, label: "Ernährung", group: "sub", color: "#4ECDC4", title: "Ausgewogene und gesunde Ernährung." },
    { id: 17, label: "Bewegung", group: "sub", color: "#4ECDC4", title: "Regelmäßige körperliche Aktivität." },
    { id: 18, label: "Schlaf", group: "sub", color: "#4ECDC4", title: "Ausreichend und erholsamer Schlaf." },
    { id: 19, label: "Yoga", group: "tools", color: "#FFEEAD", title: "Körper- und Atemübungen zur Entspannung." },
    { id: 20, label: "Fitnessstudio", group: "tools", color: "#FFEEAD", title: "Regelmäßiges Training im Fitnessstudio." },
    { id: 21, label: "Ernährungsplan", group: "tools", color: "#FFEEAD", title: "Individuell angepasster Ernährungsplan." },
    { id: 22, label: "Finanzen", group: "main", color: "#FF6B6B", x: 0, y: 200 },
    { id: 23, label: "Budgetierung", group: "sub", color: "#4ECDC4", title: "Planung und Überwachung der Einnahmen und Ausgaben." },
    { id: 24, label: "Sparen", group: "sub", color: "#4ECDC4", title: "Regelmäßiges Zurücklegen von Geld." },
    { id: 25, label: "Investieren", group: "sub", color: "#4ECDC4", title: "Langfristige Geldanlage zur Vermögensbildung." },
    { id: 26, label: "Excel", group: "tools", color: "#FFEEAD", title: "Tabellenkalkulation zur Budgetverwaltung." },
    { id: 27, label: "Finanz-Apps", group: "tools", color: "#FFEEAD", title: "Mobile Anwendungen zur Finanzverwaltung." },
    { id: 28, label: "Aktien", group: "tools", color: "#FFEEAD", title: "Investition in Wertpapiere." },
    { id: 29, label: "Kreativität", group: "main", color: "#FF6B6B", x: 0, y: -200 },
    { id: 30, label: "Malen", group: "sub", color: "#4ECDC4", title: "Ausdruck durch bildende Kunst." },
    { id: 31, label: "Schreiben", group: "sub", color: "#4ECDC4", title: "Kreatives Schreiben und Geschichtenerzählen." },
    { id: 32, label: "Musik", group: "sub", color: "#4ECDC4", title: "Musizieren und Komponieren." },
    { id: 33, label: "Procreate", group: "tools", color: "#FFEEAD", title: "Digitale Mal- und Zeichenanwendung." },
    { id: 34, label: "Ableton", group: "tools", color: "#FFEEAD", title: "Software zur Musikproduktion." },
    { id: 35, label: "Kreativ-Workshops", group: "tools", color: "#FFEEAD", title: "Workshops zur Förderung der Kreativität." }
];

const edgesData = [
    { from: 1, to: 2 },
    { from: 1, to: 3 },
    { from: 1, to: 4 },
    { from: 2, to: 7 },
    { from: 3, to: 5 },
    { from: 4, to: 6 },
    { from: 8, to: 9 },
    { from: 8, to: 10 },
    { from: 8, to: 11 },
    { from: 9, to: 14 },
    { from: 10, to: 12 },
    { from: 11, to: 13 },
    { from: 15, to: 16 },
    { from: 15, to: 17 },
    { from: 15, to: 18 },
    { from: 16, to: 21 },
    { from: 17, to: 20 },
    { from: 18, to: 19 },
    { from: 22, to: 23 },
    { from: 22, to: 24 },
    { from: 22, to: 25 },
    { from: 23, to: 26 },
    { from: 24, to: 27 },
    { from: 25, to: 28 },
    { from: 29, to: 30 },
    { from: 29, to: 31 },
    { from: 29, to: 32 },
    { from: 30, to: 33 },
    { from: 31, to: 35 },
    { from: 32, to: 34 }
];
